name: Build
on: [push, pull_request]

jobs:
  build:
    name: NickelMenu
    runs-on: ubuntu-latest
    container: docker.io/geek1011/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: make all koboroot
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: NickelMenu
        path: KoboRoot.tgz
